### ISSUE TITLE
make issues 

### ISSUE THREAD

**Issue by peterthorpe5** [rdpstaff/RDPTools#11]
Dear rdp-tools,
I have problem with (2015_june_02 downloaded) rdp-tools "make", this break fairly instantly. See what I did below:

$ git clone https://github.com/rdpstaff/RDPTools.git
$ cd RDPTools
$ git submodule init
$ git submodule update
$ make
ant -f Clustering/build.xml jar
make: execvp: ant: Permission denied
make: *** [Clustering/dist/Clustering.jar] Error 127

I am sorry if this is a daft squestion, but I am lost as to how to proceed. I dont have admin rights, so no sudo.. This is all the error produces. Any thoughts?

Kind regards,

Peter Thorpe

**Comment by rdpstaffmsu** [comment]
Hi Peter,

Since you don't have root privileges, you have two options. First option is
to talk the systems admin of computer system to help you install. If that
can't be possible, we can try option two.

Option two is to install "apache ant" in a directory where you have full
access.

run these commands below (In these instructions, $ means shell command):

1. $wget
http://mirror.reverse.net/pub/apache//ant/binaries/apache-ant-1.9.7-bin.zip
2. $unzip apache-ant-1.9.7-bin.zip
3. $cd apache-ant-1.9.7/bin
4. $pwd

copy the entire directory address

5. $cd ~
6. $vi .bashrc

In the file .bashrc, add the line below.

export PATH="path/to/apache-ant-1.9.7/bin":${PATH}
save the file

7. $source .bashrc


If you have any question, let me know.

Santosh

On Thu, Jun 2, 2016 at 9:06 AM, Peter Thorpe <notifications@github.com>
wrote:

> Dear rdp-tools,
> I have problem with rdp-tools "make", this break fairly instantly. See
> what I did below:
>
> $ git clone https://github.com/rdpstaff/RDPTools.git
> $ cd RDPTools
> $ git submodule init
> $ git submodule update
> $ make
> ant -f Clustering/build.xml jar
> make: execvp: ant: Permission denied
> make: *** [Clustering/dist/Clustering.jar] Error 127
>
> I am sorry if this is a daft squestion, but I am lost as to how to
> proceed. I dont have admin rights, so no sudo.. This is all the error
> produces. Any thoughts?
>
> Kind regards,
>
> Peter Thorpe
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rdpstaff/RDPTools/issues/11>, or mute the thread
> <https://github.com/notifications/unsubscribe/AKlEVm5fJSOQ3HU1w4xUtnyKJ-CiEDvLks5qHtVAgaJpZM4IsiIU>
> .
>



-- 
RDP Staff
Ribosomal Database Project
Center for Microbial Ecology
Michigan State University
567 Wilson Rd. Room 2225 A
East Lansing, MI 48824
(517) 353-3842

**Comment by peterthorpe5** [comment]
Thank you very much for your reply. It was very helpful.:)

Issue closed. Cheers,

Pete
