### ISSUE TITLE
Make Error: Cannot download http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz

### ISSUE THREAD

**Issue by BreadBasket95** [rdpstaff/RDPTools#19]
After following the readme download/installation instructions, the `make` command hangs up at

`download-traindata:`
 `     [get] Getting: http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
      [get] To: /home/path/to/RDPTools/classifier/build/classes/data.tgz
`

trying 

`wget http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz`

hangs up as well.

Thank you for your patience!

**Comment by lilei0202** [comment]
Hello,

I had the same issue before. 
I guess the file only could be accessed within CMU network...

In order to skip the data downloading, please comment line 48-52 and 86 in classifier/build.xml

Those lines looks like this:


line 48        
line 49        

line 86      


Hope this works for you.

Best

**Comment by gunturus** [comment]
Hi @BreadBasket95 

Sometimes we have trouble with our website due to usage and old equipment. We will try to change the method of installation.

thank you,
Santosh
